"""Pluggable open-vocabulary perception without import-time model loading."""

from __future__ import annotations

import base64
import time
from dataclasses import dataclass
from typing import Any, Callable, Iterable, Optional, Sequence, Tuple

import cv2
import numpy as np
import requests

from grutopia_extension.interactive_navigation.mapping import SemanticDetection


BBox = Tuple[float, float, float, float]


@dataclass(frozen=True)
class TargetObservationCue:
    """A DINO search proposal with geometry, never a semantic class vote."""

    target_query: str
    raw_label: str
    classified_label: str
    position: Tuple[float, float, float]
    confidence: float
    step: int

# Normalize exact aliases; do not equate monitor with television.
LABEL_ALIASES = {
    'couch': 'sofa',
    'fridge': 'refrigerator',
    'potted plant': 'plant',
    'tv': 'television',
    'tv screen': 'television',
    'television screen': 'television',
}

# Fixed second-pass vocabulary; never generated by Qwen and NOT label aliases.
# Television uses monitor/screen proposals; Qwen decides the actual class.
TARGET_SEARCH_TERMS = {
    'television': ('monitor', 'screen'),
    'refrigerator': ('fridge', 'refrigerator'),
    'chair': ('chair', 'armchair', 'stool'),
    'sofa': ('sofa', 'couch'),
}
CLASSIFICATION_LABELS = (
    'chair', 'table', 'sofa', 'door', 'cabinet', 'bed', 'lamp',
    'television', 'monitor', 'laptop', 'refrigerator', 'freezer',
    'microwave', 'oven', 'plant', 'person', 'picture', 'mirror',
    'window', 'bookshelf', 'curtain', 'vase', 'stool', 'unknown',
)




@dataclass(frozen=True)
class OpenVocabularyPerceptionConfig:
    grounding_dino_url: str = 'http://localhost:12181/gdino'
    mobile_sam_url: str = 'http://localhost:12183/mobile_sam'
    request_timeout: float = 8.0
    confidence_threshold: float = 0.25
    min_points: int = 1
    query_interval: float = 0.5
    clip_model_name: str = 'openai/clip-vit-base-patch32'
    clip_device: Optional[str] = None
    context_categories: Tuple[str, ...] = (
        'chair',
        'table',
        'sofa',
        'door',
        'cabinet',
        'bed',
        'lamp',
        'television',
        'refrigerator',
        'plant',
        'person',
    )

    semantic_classifier: str = 'clip'
    qwen_vl_url: str = 'http://localhost:12185/classify'
    qwen_vl_timeout: float = 60.0
    qwen_vl_max_candidates: int = 12
    qwen_vl_crop_margin: float = 0.15
    qwen_vl_crop_max_side: int = 384
    proposal_nms_iou: float = 0.80

    def __post_init__(self) -> None:
        if self.semantic_classifier not in ('qwen-vl', 'clip'):
            raise ValueError('semantic_classifier must be qwen-vl or clip')
        if not self.qwen_vl_url.strip() or self.qwen_vl_timeout <= 0:
            raise ValueError('Qwen-VL requires a URL and positive timeout')
        if self.qwen_vl_crop_max_side < 64 or self.qwen_vl_max_candidates < 1:
            raise ValueError('Qwen-VL crop size must be >=64 and candidate limit >=1')
        if not 0 <= self.qwen_vl_crop_margin <= 0.5 or not 0 < self.proposal_nms_iou <= 1:
            raise ValueError('invalid Qwen-VL crop margin or proposal NMS threshold')
        if self.request_timeout <= 0:
            raise ValueError('request_timeout must be positive')
        if not 0 <= self.confidence_threshold <= 1:
            raise ValueError('confidence_threshold must be between zero and one')
        if self.min_points <= 0:
            raise ValueError('min_points must be positive')
        if self.query_interval < 0:
            raise ValueError('query_interval must be non-negative')


@dataclass
class OpenVocabularyDetection:
    label: str
    confidence: float
    bbox: BBox
    mask: np.ndarray
    embedding: Optional[np.ndarray] = None
    centroid: Optional[Tuple[float, float, float]] = None
    point_count: int = 0
    step: int = 0
    raw_label: Optional[str] = None
    label_source: str = 'grounding-dino'
    classifier_model: Optional[str] = None
    classifier_response: Optional[str] = None
    proposal_source: str = 'legacy'

    def to_semantic_detection(self) -> SemanticDetection:
        """Convert the spatial portion to the mapping module's current type."""
        if self.centroid is None:
            raise ValueError('detection has no three-dimensional centroid')
        embedding = None
        if self.embedding is not None:
            embedding = tuple(float(value) for value in np.asarray(self.embedding).reshape(-1))
        return SemanticDetection(
            label=self.label,
            position=self.centroid,
            confidence=self.confidence,
            embedding=embedding,
            point_count=max(1, int(self.point_count)),
            step=int(self.step),
            sources=('open_vocabulary', 'qwen_vl') if self.label_source == 'qwen-vl' else ('open_vocabulary',),
        )


class AgentVLMBackend:
    """Short-timeout REST client for the existing Agent VLM services."""

    def __init__(
        self,
        config: Optional[OpenVocabularyPerceptionConfig] = None,
        session: Optional[Any] = None,
    ) -> None:
        self.config = config or OpenVocabularyPerceptionConfig()
        self._session = session or requests
        self.last_health_payloads: dict[str, dict] = {}

    @staticmethod
    def _encode_image(image: np.ndarray) -> str:
        ok, encoded = cv2.imencode('.jpg', image)
        if not ok:
            raise ValueError('could not encode image')
        return base64.b64encode(encoded).decode('utf-8')

    def _post(self, url: str, payload: dict) -> dict:
        response = self._session.post(
            url,
            headers={'Content-Type': 'application/json'},
            json=payload,
            timeout=self.config.request_timeout,
            proxies={'http': '', 'https': ''},
        )
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict):
            raise ValueError('VLM service returned a non-object JSON response')
        return result

    def _get(self, url: str) -> dict:
        response = self._session.get(
            url,
            timeout=self.config.request_timeout,
            proxies={'http': '', 'https': ''},
        )
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict):
            raise ValueError('VLM health endpoint returned a non-object JSON response')
        return result

    def check_ready(self) -> dict:
        """Fail fast unless both HTTP perception services report ready."""

        status = {}
        endpoints = {
            'grounding_dino': self.config.grounding_dino_url,
            'mobile_sam': self.config.mobile_sam_url,
        }
        if self.config.semantic_classifier == 'qwen-vl':
            endpoints['qwen_vl'] = self.config.qwen_vl_url
        for name, endpoint in endpoints.items():
            health_url = endpoint.rsplit('/', 1)[0] + '/health'
            payload = self._get(health_url)
            if payload.get('ready') is not True:
                raise RuntimeError(f'{name} service is not ready at {health_url}')
            status[name] = health_url
            self.last_health_payloads[name] = {
                'url': health_url,
                **{
                    key: payload[key] for key in (
                        'service', 'model', 'checkpoint', 'box_threshold', 'text_threshold',
                        'max_pixels', 'max_new_tokens',
                    ) if key in payload
                },
            }
        return status

    def detect(self, image: np.ndarray, caption: str) -> list[dict]:
        result = self._post(
            self.config.grounding_dino_url,
            {'image': self._encode_image(image), 'caption': caption},
        )
        boxes = result.get('boxes', ())
        scores = result.get('logits', result.get('scores', ()))
        labels = result.get('phrases', result.get('labels', ()))
        if not (len(boxes) == len(scores) == len(labels)):
            raise ValueError('GroundingDINO response arrays have different lengths')
        return [
            {'bbox': box, 'confidence': float(np.asarray(score).max()), 'label': str(label)}
            for box, score, label in zip(boxes, scores, labels)
        ]

    def classify(self, image: np.ndarray, labels: Sequence[str]) -> dict:
        # This service runs in the VL environment, not inside Isaac Sim.
        response = self._session.post(
            self.config.qwen_vl_url,
            json={'image': self._encode_image(image), 'labels': list(labels)},
            timeout=self.config.qwen_vl_timeout,
            proxies={'http': '', 'https': ''},
        )
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict) or result.get('label') not in labels:
            raise ValueError('Qwen-VL returned an invalid classification response')
        if not isinstance(result.get('model'), str) or not result['model'].strip():
            raise ValueError('Qwen-VL response is missing model provenance')
        return result

    def segment(self, image: np.ndarray, bbox: Sequence[float]) -> np.ndarray:
        result = self._post(
            self.config.mobile_sam_url,
            {'image': self._encode_image(image), 'bbox': [float(value) for value in bbox]},
        )
        encoded = result.get('cropped_mask')
        if not isinstance(encoded, str):
            raise ValueError('MobileSAM response is missing cropped_mask')
        raw = base64.b64decode(encoded, validate=True)
        expected_size = int(np.prod(image.shape[:2]))
        mask = np.frombuffer(raw, dtype=np.uint8)
        if mask.size != expected_size:
            raise ValueError(f'MobileSAM mask has {mask.size} pixels; expected {expected_size}')
        return mask.reshape(image.shape[:2]).astype(bool)


class OpenVocabularyPerception:
    """Detect, segment, embed, and associate image objects with world points."""

    def __init__(
        self,
        config: Optional[OpenVocabularyPerceptionConfig] = None,
        detector: Optional[Any] = None,
        segmenter: Optional[Any] = None,
        embedder: Optional[Callable[[np.ndarray], np.ndarray]] = None,
        simulator_fallback: Optional[Callable[..., Iterable[Any]]] = None,
        clock: Callable[[], float] = time.monotonic,
        classifier: Optional[Any] = None,
    ) -> None:
        self.config = config or OpenVocabularyPerceptionConfig()
        backend = None
        if detector is None or segmenter is None:
            backend = AgentVLMBackend(self.config)
        self.detector = detector if detector is not None else backend
        self.segmenter = segmenter if segmenter is not None else backend
        self.classifier = classifier if classifier is not None else (backend or AgentVLMBackend(self.config))
        self.embedder = embedder
        self.simulator_fallback = simulator_fallback
        self._clock = clock
        self._last_query_time = float('-inf')
        self._last_query: Optional[str] = None
        self._last_result: list[Any] = []
        self._clip_processor: Optional[Any] = None
        self._clip_model: Optional[Any] = None
        self._clip_device: Optional[str] = None
        self.last_item_errors: list[dict] = []
        self.last_query_status = 'idle'
        self.last_target_cues: list[TargetObservationCue] = []
        # One small, JSON-serializable record for the camera frame most
        # recently sent to GroundingDINO. Never reuse it for a later step.
        self.last_debug_frame: Optional[dict] = None

    def check_ready(self, load_clip: bool = True) -> dict:
        """Validate remote services and local CLIP before a long run starts."""

        services = {}
        checked = set()
        for component in (self.detector, self.segmenter):
            if id(component) in checked:
                continue
            checked.add(id(component))
            checker = getattr(component, 'check_ready', None)
            if checker is not None:
                result = checker()
                if isinstance(result, dict):
                    services.update(result)
        load_clip = load_clip and self.config.semantic_classifier == 'clip'
        if load_clip and self.embedder is None:
            self._ensure_clip()
        return {
            'services': services,
            'clip_device': self._clip_device if load_clip else None,
        }

    def build_query(self, target: str, include_context: bool = True) -> str:
        if self.config.semantic_classifier == 'qwen-vl':
            # Pass 1 is context only. Remove the current target and its search words.
            excluded = set(self._target_labels(target))
            for part in tuple(excluded):
                excluded.update(TARGET_SEARCH_TERMS.get(part, (part,)))
            labels = (*self.config.context_categories, 'monitor', 'screen', 'picture', 'mirror', 'window', 'bookshelf', 'curtain', 'microwave') if include_context else ()
            normalized = (' '.join(label.casefold().split()) for label in labels)
            unique = list(dict.fromkeys(
                label for label in normalized if LABEL_ALIASES.get(label, label) not in excluded
            ))
            return ' . '.join(unique)
        # Preserve the legacy single-pass CLIP mode.
        labels = [part.strip() for part in target.replace('|', '.').split('.') if part.strip()]
        if include_context:
            labels.extend(self.config.context_categories)
        normalized = (' '.join(label.casefold().split()) for label in labels)
        normalized = (LABEL_ALIASES.get(label, label) for label in normalized)
        unique = list(dict.fromkeys(normalized))
        return ' . '.join(unique) + (' .' if unique else '')

    def build_target_query(self, target: str) -> str:
        """Pass 2: a small deterministic caption, separate from environment words."""
        terms = []
        for label in self._target_labels(target):
            terms.extend(TARGET_SEARCH_TERMS.get(label, (label,)))
        if not terms:
            raise ValueError('target query cannot be empty')
        return ' . '.join(dict.fromkeys(terms))

    @staticmethod
    def _target_labels(target: str) -> list[str]:
        parts = (' '.join(part.casefold().split()) for part in target.replace('|', '.').split('.'))
        return list(dict.fromkeys(LABEL_ALIASES.get(part, part) for part in parts if part))

    def perceive(
        self,
        rgba: np.ndarray,
        depth: np.ndarray,
        point_image: np.ndarray,
        target: str,
        include_context: bool = True,
        step: int = 0,
    ) -> list[Any]:
        self.last_item_errors = []
        self.last_debug_frame = None
        self.last_target_cues = []
        rgb, depth_array, points = self._validate_inputs(rgba, depth, point_image)
        query = self.build_query(target, include_context=include_context)
        queries = [('legacy', query)]
        if self.config.semantic_classifier == 'qwen-vl':
            queries = ([('context', query)] if query else []) + [('target', self.build_target_query(target))]
        query_key = (tuple(self._target_labels(target)), tuple(queries))
        now = self._clock()
        debug_frame = {
            'step': int(step),
            'status': 'requested',
            'query': query,
            'queries': [{'source': name, 'caption': caption} for name, caption in queries],
            'target_query': target,
            'classifier': self.config.semantic_classifier,
            'image_size': [int(rgb.shape[1]), int(rgb.shape[0])],
            'boxes': [],
            'mapped': [],
            'classified': [],
            'target_cues': [],
            'item_errors': [],
        }
        self.last_debug_frame = debug_frame
        if query_key == self._last_query and now - self._last_query_time < self.config.query_interval:
            # A materialized detection contains geometry from a particular
            # RGB/depth frame. Replaying it would submit a stale world-space
            # centroid as a new observation when either the camera or object
            # has moved. Rate limiting therefore skips this frame instead of
            # caching three-dimensional observations.
            self.last_query_status = 'rate_limited'
            debug_frame['status'] = 'rate_limited'
            return []

        try:
            detections, proposal_sources = [], []
            for name, caption in queries:
                proposals = self._run_detector(rgb, caption)
                boxes = self._debug_detector_boxes(proposals, rgb.shape[:2])
                debug_frame['boxes'].extend({**box, 'proposal_source': name} for box in boxes)
                detections.extend(proposals)
                proposal_sources.extend([name] * len(proposals))
            result = self._materialize(detections, rgb, depth_array, points, step=step, target=target, proposal_sources=proposal_sources)
            debug_frame['mapped'] = [
                {
                    'label': detection.label,
                    'raw_label': detection.raw_label,
                    'label_source': detection.label_source,
                    'classifier_model': detection.classifier_model,
                    'classifier_response': detection.classifier_response,
                    'proposal_source': detection.proposal_source,
                    'confidence': detection.confidence,
                    'bbox_xyxy': [float(value) for value in detection.bbox],
                    'centroid': [float(value) for value in detection.centroid],
                    'point_count': int(detection.point_count),
                }
                for detection in result
                if isinstance(detection, OpenVocabularyDetection)
                and detection.centroid is not None
            ]
            debug_frame['item_errors'] = list(self.last_item_errors)
            debug_frame['status'] = 'ok'
            self.last_query_status = 'ok'
        except Exception as error:
            debug_frame['item_errors'] = list(self.last_item_errors)
            debug_frame['status'] = 'failed'
            debug_frame['error'] = {
                'type': type(error).__name__,
                'message': str(error),
            }
            self.last_query_status = 'failed'
            if self.simulator_fallback is None:
                raise
            else:
                result = list(
                    self.simulator_fallback(
                        rgba=rgba,
                        depth=depth,
                        point_image=point_image,
                        query=query,
                    )
                )
                self.last_query_status = 'fallback'
                debug_frame['status'] = 'fallback'

        self._last_query_time = now
        self._last_query = query_key
        self._last_result = list(result)
        return result

    def _debug_detector_boxes(self, detections: Iterable[Any], image_shape: tuple[int, int]) -> list[dict]:
        """Retain DINO boxes before thresholding, masking, and map association."""

        boxes = []
        for raw in detections:
            try:
                label, confidence, bbox = self._parse_detection(raw, image_shape)
                boxes.append({
                    'label': label,
                    'confidence': float(confidence),
                    'bbox_xyxy': [float(value) for value in bbox],
                    'above_threshold': bool(confidence >= self.config.confidence_threshold),
                })
            except Exception as error:
                boxes.append({
                    'label': self._raw_label(raw),
                    'error': f'{type(error).__name__}: {error}',
                })
        return boxes

    def as_semantic_detections(self, detections: Iterable[OpenVocabularyDetection]) -> list[SemanticDetection]:
        return [detection.to_semantic_detection() for detection in detections if detection.centroid is not None]

    @staticmethod
    def _validate_inputs(
        rgba: np.ndarray,
        depth: np.ndarray,
        point_image: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        image = np.asarray(rgba)
        if image.ndim != 3 or image.shape[2] not in (3, 4):
            raise ValueError('rgba must have shape (height, width, 3 or 4)')
        depth_array = np.asarray(depth)
        points = np.asarray(point_image)
        if depth_array.shape != image.shape[:2]:
            raise ValueError('depth must align pixel-for-pixel with rgba')
        if points.shape != (*image.shape[:2], 3):
            raise ValueError('point_image must have shape (height, width, 3)')
        return np.ascontiguousarray(image[..., :3]), depth_array, points

    def _run_detector(self, image: np.ndarray, query: str) -> list[dict]:
        detector = self.detector
        if hasattr(detector, 'detect'):
            raw = detector.detect(image, query)
        elif hasattr(detector, 'predict'):
            raw = detector.predict(image, caption=query)
        else:
            raw = detector(image, query)
        if isinstance(raw, dict):
            boxes = raw.get('boxes', ())
            scores = raw.get('logits', raw.get('scores', ()))
            labels = raw.get('phrases', raw.get('labels', ()))
            raw = [
                {'bbox': box, 'confidence': float(np.asarray(score).max()), 'label': label}
                for box, score, label in zip(boxes, scores, labels)
            ]
        elif hasattr(raw, 'boxes') and hasattr(raw, 'logits') and hasattr(raw, 'phrases'):
            raw = [
                {'bbox': box, 'confidence': float(np.asarray(score).max()), 'label': label}
                for box, score, label in zip(raw.boxes, raw.logits, raw.phrases)
            ]
        return list(raw)

    def _materialize(self, raw_detections, image, depth, point_image, step=0, target='', proposal_sources=None):
        output, proposals = [], []
        raw_detections = list(raw_detections)
        if proposal_sources is not None and len(proposal_sources) != len(raw_detections):
            raise ValueError('proposal sources must align with detections')
        for index, raw in enumerate(raw_detections):
            label = self._raw_label(raw)
            try:
                label, confidence, bbox = self._parse_detection(raw, image.shape[:2])
                if confidence < self.config.confidence_threshold or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
                    continue
                proposals.append((label, confidence, bbox, proposal_sources[index] if proposal_sources else 'legacy'))
            except Exception as error:
                self.last_item_errors.append({'label': label, 'type': type(error).__name__, 'message': str(error)})
        use_vl = self.config.semantic_classifier == 'qwen-vl'
        if use_vl:
            proposals = self._select_proposals(proposals, step)
        categories = list(dict.fromkeys((*CLASSIFICATION_LABELS, *self._target_labels(target))))
        for label, confidence, bbox, proposal_source in proposals:
            try:
                mask = self._run_segmenter(image, bbox)
                if mask.shape != image.shape[:2]:
                    raise ValueError('segmenter mask must align pixel-for-pixel with the input')
                valid = mask & np.isfinite(depth) & (depth > 0) & np.isfinite(point_image).all(axis=-1)
                world_points = point_image[valid]
                if len(world_points) < self.config.min_points:
                    continue
                centroid = tuple(float(v) for v in world_points.mean(axis=0))
                classification = {}
                if use_vl:
                    classification = self.classifier.classify(self._qwen_context_crop(image, bbox), categories)
                    final_label = classification.get('label')
                    if final_label not in categories or not classification.get('model'):
                        raise ValueError('classifier returned invalid category or missing model provenance')
                    if self.last_debug_frame is not None:
                        self.last_debug_frame['classified'].append({
                            'raw_label': label, 'label': final_label,
                            'bbox_xyxy': list(bbox), 'proposal_source': proposal_source,
                            'classifier_model': classification['model'],
                            'classifier_response': classification.get('raw_text'),
                            'reason': classification.get('reason', 'classified'),
                            'accepted': final_label != 'unknown',
                        })
                    if proposal_source == 'target':
                        cue = TargetObservationCue(
                            target_query=str(target), raw_label=label,
                            classified_label=final_label, position=centroid,
                            confidence=float(confidence), step=int(step),
                        )
                        self.last_target_cues.append(cue)
                        if self.last_debug_frame is not None:
                            self.last_debug_frame['target_cues'].append({
                                'raw_label': label, 'classified_label': final_label,
                                'centroid': list(centroid), 'confidence': float(confidence),
                                'step': int(step),
                            })
                    if final_label == 'unknown':
                        continue
                    embedding = None
                else:
                    embedding = self._embed_masked_crop(image, mask)
                    final_label = label
                output.append(OpenVocabularyDetection(
                    label=final_label, confidence=confidence, bbox=bbox, mask=mask, embedding=embedding,
                    centroid=centroid, point_count=len(world_points), step=int(step),
                    raw_label=label,
                    label_source='qwen-vl' if use_vl else 'grounding-dino',
                    classifier_model=classification.get('model'), classifier_response=classification.get('raw_text'),
                    proposal_source=proposal_source,
                ))
            except Exception as error:
                self.last_item_errors.append({'label': label, 'type': type(error).__name__, 'message': str(error)})
        if self.last_item_errors and not output:
            first = self.last_item_errors[0]
            raise RuntimeError(f'all materialized detections failed; first error for {first["label"]!r}: {first["type"]}: {first["message"]}')
        return output


    def _select_proposals(self, proposals: list, step: int) -> list:
        """Cheap class-agnostic NMS before either SAM or VL is called."""

        def iou(a, b):
            intersection = max(0.0, min(a[2], b[2]) - max(a[0], b[0])) * max(0.0, min(a[3], b[3]) - max(a[1], b[1]))
            union = (a[2] - a[0]) * (a[3] - a[1]) + (b[2] - b[0]) * (b[3] - b[1]) - intersection
            return intersection / union if union > 0 else 0.0
        kept = []
        for proposal in sorted(proposals, key=lambda item: (item[3] == 'target', item[1]), reverse=True):
            label, _, bbox, source = proposal
            if any((iou(bbox, other[2]) >= self.config.proposal_nms_iou for other in kept)):
                continue
            if len(kept) >= self.config.qwen_vl_max_candidates:
                continue
            kept.append(proposal)
        return kept

    def _qwen_context_crop(self, image: np.ndarray, bbox: BBox) -> np.ndarray:
        """Preserve real RGB background; mark the original bbox inside a padded crop."""
        height, width = image.shape[:2]
        x1, y1, x2, y2 = bbox
        margin = self.config.qwen_vl_crop_margin
        left = max(0, int(np.floor(x1 - margin * (x2 - x1))))
        top = max(0, int(np.floor(y1 - margin * (y2 - y1))))
        right = min(width, int(np.ceil(x2 + margin * (x2 - x1))))
        bottom = min(height, int(np.ceil(y2 + margin * (y2 - y1))))
        crop = image[top:bottom, left:right].copy()
        if crop.size == 0:
            raise ValueError('cannot classify an empty context crop')
        cv2.rectangle(crop, (max(0, int(x1) - left), max(0, int(y1) - top)), (min(right - left - 1, int(x2) - left), min(bottom - top - 1, int(y2) - top)), (255, 0, 0), 1)
        scale = min(1.0, self.config.qwen_vl_crop_max_side / max(crop.shape[:2]))
        if scale < 1.0:
            crop = cv2.resize(crop, (max(1, round(crop.shape[1] * scale)), max(1, round(crop.shape[0] * scale))), interpolation=cv2.INTER_AREA)
        return np.ascontiguousarray(crop)



    @staticmethod
    def _raw_label(raw: Any) -> str:
        if isinstance(raw, OpenVocabularyDetection):
            return raw.label
        if isinstance(raw, dict):
            return str(raw.get('label', raw.get('phrase', 'object')))
        if isinstance(raw, (tuple, list)) and raw:
            return str(raw[0])
        return 'unknown'

    @staticmethod
    def _parse_detection(raw: Any, image_shape: tuple[int, int]) -> tuple[str, float, BBox]:
        if isinstance(raw, OpenVocabularyDetection):
            return raw.label, raw.confidence, raw.bbox
        if isinstance(raw, dict):
            label = str(raw.get('label', raw.get('phrase', 'object')))
            confidence = float(raw.get('confidence', raw.get('score', raw.get('logit', 1.0))))
            box = np.array(raw.get('bbox', raw.get('box')), dtype=float, copy=True)
        else:
            label, confidence, box = raw
            box = np.array(box, dtype=float, copy=True)
        if box.shape != (4,) or not np.isfinite(box).all():
            raise ValueError('detector bbox must contain four finite values')
        height, width = image_shape
        if np.max(np.abs(box)) <= 1.5:
            box = box * np.array([width, height, width, height], dtype=float)
        box[[0, 2]] = np.clip(box[[0, 2]], 0, width)
        box[[1, 3]] = np.clip(box[[1, 3]], 0, height)
        return label, confidence, tuple(float(value) for value in box)

    def _run_segmenter(self, image: np.ndarray, bbox: BBox) -> np.ndarray:
        segmenter = self.segmenter
        if hasattr(segmenter, 'segment'):
            mask = segmenter.segment(image, bbox)
        elif hasattr(segmenter, 'segment_bbox'):
            mask = segmenter.segment_bbox(image, list(bbox))
        else:
            mask = segmenter(image, bbox)
        return np.asarray(mask, dtype=bool)

    def _embed_masked_crop(self, image: np.ndarray, mask: np.ndarray) -> np.ndarray:
        rows, columns = np.nonzero(mask)
        if not len(rows):
            raise ValueError('cannot embed an empty mask')
        y1, y2 = rows.min(), rows.max() + 1
        x1, x2 = columns.min(), columns.max() + 1
        crop = image[y1:y2, x1:x2].copy()
        crop[~mask[y1:y2, x1:x2]] = 0
        vector = self.embedder(crop) if self.embedder is not None else self._clip_embed(crop)
        embedding = np.asarray(vector, dtype=np.float32).reshape(-1)
        norm = float(np.linalg.norm(embedding))
        if not np.isfinite(norm) or norm == 0:
            raise ValueError('embedder returned a zero or non-finite vector')
        return embedding / norm

    def _clip_embed(self, crop: np.ndarray) -> np.ndarray:
        self._ensure_clip()
        import torch

        inputs = self._clip_processor(images=crop, return_tensors='pt')
        inputs = {name: value.to(self._clip_device) for name, value in inputs.items()}
        with torch.inference_mode():
            features = self._clip_model.get_image_features(**inputs)
        return features[0].detach().cpu().numpy()

    def embed_text(self, text: str) -> np.ndarray:
        """Return a normalized CLIP text embedding for open-vocabulary matching."""

        if not str(text).strip():
            raise ValueError('text cannot be empty')
        self._ensure_clip()
        import torch

        inputs = self._clip_processor(text=[str(text)], return_tensors='pt', padding=True)
        inputs = {name: value.to(self._clip_device) for name, value in inputs.items()}
        with torch.inference_mode():
            features = self._clip_model.get_text_features(**inputs)
        embedding = features[0].detach().cpu().numpy().astype(np.float32)
        norm = float(np.linalg.norm(embedding))
        if not np.isfinite(norm) or norm <= 1e-12:
            raise ValueError('CLIP returned an invalid text embedding')
        return embedding / norm

    def _ensure_clip(self):
        if self._clip_model is None:
            import torch
            from transformers import CLIPModel, CLIPProcessor

            device = self.config.clip_device or ('cuda' if torch.cuda.is_available() else 'cpu')
            self._clip_processor = CLIPProcessor.from_pretrained(
                self.config.clip_model_name,
                local_files_only=True,
            )
            self._clip_model = CLIPModel.from_pretrained(
                self.config.clip_model_name,
                local_files_only=True,
            ).to(device)
            self._clip_model.eval()
            self._clip_device = device


__all__ = [
    'AgentVLMBackend',
    'OpenVocabularyDetection',
    'OpenVocabularyPerception',
    'OpenVocabularyPerceptionConfig',
]
