"""Pluggable open-vocabulary perception without import-time model loading."""

from __future__ import annotations

import base64
import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable, Optional, Sequence, Tuple

import cv2
import numpy as np
import requests

from grutopia_extension.interactive_navigation.mapping import SemanticDetection


BBox = Tuple[float, float, float, float]

# These are visual confusion candidates, not labels read from the scene.
LABEL_REVIEW_GROUPS = (
    ('bed', 'sofa', 'chair'),
    ('cabinet', 'refrigerator'),
    ('plant', 'person'),
    ('television', 'monitor'),
)
LABEL_ALIASES = {
    'couch': 'sofa',
    'fridge': 'refrigerator',
    'potted plant': 'plant',
    'tv': 'television',
    'tv screen': 'television',
    'television screen': 'television',
}

# Fixed second-pass vocabulary; never generated by Qwen and NOT label aliases.
# The TV caption deliberately excludes television, matching the single-image A/B result.
TARGET_SEARCH_TERMS = {
    'television': ('monitor', 'screen'),
    'refrigerator': ('fridge', 'refrigerator'),
    'chair': ('chair', 'armchair', 'stool'),
    'sofa': ('sofa', 'couch'),
}
CLASSIFICATION_LABELS = (
    'chair', 'table', 'sofa', 'door', 'cabinet', 'bed', 'lamp',
    'television', 'monitor', 'laptop', 'refrigerator', 'freezer',
    'microwave', 'oven', 'plant', 'person', 'picture', 'mirror',
    'window', 'bookshelf', 'curtain', 'vase', 'stool', 'unknown',
)


@dataclass(frozen=True)
class OpenVocabularyPerceptionConfig:
    grounding_dino_url: str = 'http://localhost:12181/gdino'
    mobile_sam_url: str = 'http://localhost:12183/mobile_sam'
    request_timeout: float = 8.0
    confidence_threshold: float = 0.25
    min_points: int = 1
    query_interval: float = 0.5
    clip_model_name: str = 'openai/clip-vit-base-patch32'
    clip_device: Optional[str] = None
    strict_errors: bool = False
    semantic_classifier: str = 'qwen-vl'
    qwen_vl_url: str = 'http://localhost:12185/classify'
    qwen_vl_timeout: float = 60.0
    qwen_vl_crop_margin: float = 0.15
    qwen_vl_crop_max_side: int = 384
    qwen_vl_max_candidates: int = 12
    proposal_nms_iou: float = 0.80
    screen_edge_strip_aspect_ratio: float = 4.0
    screen_edge_strip_min_span: float = 0.80
    context_categories: Tuple[str, ...] = (
        'chair',
        'table',
        'sofa',
        'door',
        'cabinet',
        'bed',
        'lamp',
        'television',
        'refrigerator',
        'plant',
        'person',
        'monitor',
        'screen',
        'picture',
        'mirror',
        'window',
        'bookshelf',
        'curtain',
        'microwave',
    )
    label_refinement: bool = True
    # Cosine thresholds are conservative starting values, not probabilities.
    label_refinement_margin: float = 0.08
    label_refinement_min_similarity: float = 0.25
    label_audit_path: Optional[str] = None

    def __post_init__(self) -> None:
        if self.semantic_classifier not in ('qwen-vl', 'clip'):
            raise ValueError('semantic_classifier must be qwen-vl or clip')
        if not self.qwen_vl_url.strip() or self.qwen_vl_timeout <= 0:
            raise ValueError('Qwen-VL requires a URL and positive timeout')
        if not 0 <= self.qwen_vl_crop_margin <= 0.5:
            raise ValueError('qwen_vl_crop_margin must be in [0, 0.5]')
        if self.qwen_vl_crop_max_side < 64 or self.qwen_vl_max_candidates < 1:
            raise ValueError('Qwen-VL crop size must be >=64 and candidate limit >=1')
        if not 0 < self.proposal_nms_iou <= 1:
            raise ValueError('proposal_nms_iou must be in (0, 1]')
        if self.screen_edge_strip_aspect_ratio <= 1:
            raise ValueError('screen_edge_strip_aspect_ratio must exceed one')
        if not 0 < self.screen_edge_strip_min_span <= 1:
            raise ValueError('screen_edge_strip_min_span must be in (0, 1]')
        if self.request_timeout <= 0:
            raise ValueError('request_timeout must be positive')
        if not 0 <= self.confidence_threshold <= 1:
            raise ValueError('confidence_threshold must be between zero and one')
        if self.min_points <= 0:
            raise ValueError('min_points must be positive')
        if self.query_interval < 0:
            raise ValueError('query_interval must be non-negative')
        if not 0 < self.label_refinement_margin <= 2:
            raise ValueError('label_refinement_margin must be in (0, 2]')
        if not -1 <= self.label_refinement_min_similarity <= 1:
            raise ValueError('label_refinement_min_similarity must be between -1 and 1')


@dataclass
class OpenVocabularyDetection:
    label: str
    confidence: float
    bbox: BBox
    mask: np.ndarray
    embedding: Optional[np.ndarray] = None
    centroid: Optional[Tuple[float, float, float]] = None
    point_count: int = 0
    step: int = 0
    raw_label: Optional[str] = None
    label_refinement_reason: str = 'not_reviewed'
    clip_label_scores: dict[str, float] = field(default_factory=dict)
    label_source: str = 'grounding-dino'
    classifier_model: Optional[str] = None
    classifier_response: Optional[str] = None
    proposal_source: str = 'legacy'
    semantic_eligible: bool = True
    evidence_reason: str = 'accepted'

    def to_semantic_detection(self) -> SemanticDetection:
        """Convert the spatial portion to the mapping module's current type."""
        if self.centroid is None:
            raise ValueError('detection has no three-dimensional centroid')
        if not self.semantic_eligible:
            raise ValueError('ambiguous partial detection cannot supply semantic evidence')
        embedding = None
        if self.embedding is not None:
            embedding = tuple(float(value) for value in np.asarray(self.embedding).reshape(-1))
        return SemanticDetection(
            label=self.label,
            position=self.centroid,
            confidence=self.confidence,
            embedding=embedding,
            point_count=max(1, int(self.point_count)),
            step=int(self.step),
        )


class AgentVLMBackend:
    """Short-timeout REST client for the existing Agent VLM services."""

    def __init__(
        self,
        config: Optional[OpenVocabularyPerceptionConfig] = None,
        session: Optional[Any] = None,
    ) -> None:
        self.config = config or OpenVocabularyPerceptionConfig()
        self._session = session or requests

    @staticmethod
    def _encode_image(image: np.ndarray) -> str:
        ok, encoded = cv2.imencode('.jpg', image)
        if not ok:
            raise ValueError('could not encode image')
        return base64.b64encode(encoded).decode('utf-8')

    def _post(self, url: str, payload: dict) -> dict:
        response = self._session.post(
            url,
            headers={'Content-Type': 'application/json'},
            json=payload,
            timeout=self.config.request_timeout,
            proxies={'http': '', 'https': ''},
        )
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict):
            raise ValueError('VLM service returned a non-object JSON response')
        return result

    def detect(self, image: np.ndarray, caption: str) -> list[dict]:
        result = self._post(
            self.config.grounding_dino_url,
            {'image': self._encode_image(image), 'caption': caption},
        )
        boxes = result.get('boxes', ())
        scores = result.get('logits', result.get('scores', ()))
        labels = result.get('phrases', result.get('labels', ()))
        if not (len(boxes) == len(scores) == len(labels)):
            raise ValueError('GroundingDINO response arrays have different lengths')
        return [
            {'bbox': box, 'confidence': float(np.asarray(score).max()), 'label': str(label)}
            for box, score, label in zip(boxes, scores, labels)
        ]

    def classify(self, image: np.ndarray, labels: Sequence[str]) -> dict:
        # This service runs in the VL environment, not inside Isaac Sim.
        response = self._session.post(
            self.config.qwen_vl_url,
            json={'image': self._encode_image(image), 'labels': list(labels)},
            timeout=self.config.qwen_vl_timeout,
            proxies={'http': '', 'https': ''},
        )
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict) or result.get('label') not in labels:
            raise ValueError('Qwen-VL returned an invalid classification response')
        if not isinstance(result.get('model'), str) or not result['model'].strip():
            raise ValueError('Qwen-VL response is missing model provenance')
        return result

    def segment(self, image: np.ndarray, bbox: Sequence[float]) -> np.ndarray:
        result = self._post(
            self.config.mobile_sam_url,
            {'image': self._encode_image(image), 'bbox': [float(value) for value in bbox]},
        )
        encoded = result.get('cropped_mask')
        if not isinstance(encoded, str):
            raise ValueError('MobileSAM response is missing cropped_mask')
        raw = base64.b64decode(encoded, validate=True)
        expected_size = int(np.prod(image.shape[:2]))
        mask = np.frombuffer(raw, dtype=np.uint8)
        if mask.size != expected_size:
            raise ValueError(f'MobileSAM mask has {mask.size} pixels; expected {expected_size}')
        return mask.reshape(image.shape[:2]).astype(bool)


class OpenVocabularyPerception:
    """Detect, segment, embed, and associate image objects with world points."""

    def __init__(
        self,
        config: Optional[OpenVocabularyPerceptionConfig] = None,
        detector: Optional[Any] = None,
        segmenter: Optional[Any] = None,
        embedder: Optional[Callable[[np.ndarray], np.ndarray]] = None,

        simulator_fallback: Optional[Callable[..., Iterable[Any]]] = None,
        clock: Callable[[], float] = time.monotonic,
    ) -> None:
        self.config = config or OpenVocabularyPerceptionConfig()
        backend = None
        if detector is None or segmenter is None:
            backend = AgentVLMBackend(self.config)
        self.detector = detector if detector is not None else backend
        self.segmenter = segmenter if segmenter is not None else backend
        self.embedder = embedder
        self.simulator_fallback = simulator_fallback
        self.classifier = AgentVLMBackend(self.config)
        self._clock = clock
        self._last_query_time = float('-inf')
        self._last_query: Optional[tuple] = None
        self._last_result: list[Any] = []
        self._clip_processor: Optional[Any] = None
        self._clip_model: Optional[Any] = None
        self._clip_device: Optional[str] = None
        self._label_text_matrices: dict[tuple[str, ...], np.ndarray] = {}
        self._label_audit_ready = False

    def build_query(self, target: str, include_context: bool = True) -> str:
        if self.config.semantic_classifier == 'qwen-vl':
            # Pass 1 is context only. Remove the current target and its search words.
            excluded = set(self._target_labels(target))
            for part in tuple(excluded):
                excluded.update(TARGET_SEARCH_TERMS.get(part, (part,)))
            labels = self.config.context_categories if include_context else ()
            normalized = (' '.join(label.casefold().split()) for label in labels)
            unique = list(dict.fromkeys(
                label for label in normalized if LABEL_ALIASES.get(label, label) not in excluded
            ))
            return ' . '.join(unique)
        # Preserve the legacy single-pass CLIP mode.
        labels = [part.strip() for part in target.replace('|', '.').split('.') if part.strip()]
        if include_context:
            labels.extend(self.config.context_categories)
        normalized = (' '.join(label.casefold().split()) for label in labels)
        normalized = (LABEL_ALIASES.get(label, label) for label in normalized)
        unique = list(dict.fromkeys(normalized))
        return ' . '.join(unique) + (' .' if unique else '')

    def build_target_query(self, target: str) -> str:
        """Pass 2: a small deterministic caption, separate from environment words."""
        terms = []
        for label in self._target_labels(target):
            terms.extend(TARGET_SEARCH_TERMS.get(label, (label,)))
        if not terms:
            raise ValueError('target query cannot be empty')
        return ' . '.join(dict.fromkeys(terms))

    @staticmethod
    def _target_labels(target: str) -> list[str]:
        parts = (' '.join(part.casefold().split()) for part in target.replace('|', '.').split('.'))
        return list(dict.fromkeys(LABEL_ALIASES.get(part, part) for part in parts if part))

    def perceive(
        self,
        rgba: np.ndarray,
        depth: np.ndarray,
        point_image: np.ndarray,
        target: str,
        include_context: bool = True,
        step: int = 0,
    ) -> list[Any]:
        rgb, depth_array, points = self._validate_inputs(rgba, depth, point_image)
        query = self.build_query(target, include_context=include_context)
        if self.config.semantic_classifier == 'qwen-vl':
            queries = [('context', query)] if query else []
            queries.append(('target', self.build_target_query(target)))
        else:
            queries = [('legacy', query)]
        # The cache must distinguish both captions AND the final semantic target.
        query_key = (tuple(self._target_labels(target)), tuple(queries))
        now = self._clock()
        if query_key == self._last_query and now - self._last_query_time < self.config.query_interval:
            return list(self._last_result)

        try:
            detections, proposal_sources = [], []
            # Both passes use the SAME RGB snapshot. Merge before SAM/VL processing.
            for source, caption in queries:
                print(
                    f"[GDINO_REQUEST] step={step} pass={source} shape={rgb.shape} caption={caption!r}",
                    flush=True,
                )
                pass_detections = self._run_detector(rgb, caption)
                print(
                    f"[GDINO_RESPONSE] step={step} pass={source} count={len(pass_detections)} "
                    f"detections={pass_detections!r}",
                    flush=True,
                )
                detections.extend(pass_detections)
                proposal_sources.extend([source] * len(pass_detections))
            result = self._materialize(
                detections, rgb, depth_array, points, step=step, target=target,
                proposal_sources=proposal_sources,
            )
            self._write_label_audit(result)
        except Exception:
            if self.config.strict_errors or self.config.semantic_classifier == 'qwen-vl':
                raise
            if self.simulator_fallback is None:
                result = []
            else:
                result = list(
                    self.simulator_fallback(
                        rgba=rgba,
                        depth=depth,
                        point_image=point_image,
                        query=query,
                    )
                )

        self._last_query_time = now
        self._last_query = query_key
        self._last_result = list(result)
        return result

    def as_semantic_detections(self, detections: Iterable[OpenVocabularyDetection]) -> list[SemanticDetection]:
        return [detection.to_semantic_detection() for detection in detections
                if detection.centroid is not None and detection.semantic_eligible]

    @staticmethod
    def _validate_inputs(
        rgba: np.ndarray,
        depth: np.ndarray,
        point_image: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        image = np.asarray(rgba)    

        if image.ndim != 3 or image.shape[2] not in (3, 4):
            raise ValueError('rgba must have shape (height, width, 3 or 4)')
        depth_array = np.asarray(depth)
        points = np.asarray(point_image)
        if depth_array.shape != image.shape[:2]:
            raise ValueError('depth must align pixel-for-pixel with rgba')
        if points.shape != (*image.shape[:2], 3):
            raise ValueError('point_image must have shape (height, width, 3)')
        return np.ascontiguousarray(image[..., :3]), depth_array, points

    def _run_detector(self, image: np.ndarray, query: str) -> list[dict]:
        detector = self.detector
        if hasattr(detector, 'detect'):
            raw = detector.detect(image, query)
        elif hasattr(detector, 'predict'):
            raw = detector.predict(image, caption=query)
        else:
            raw = detector(image, query)
        if isinstance(raw, dict):
            boxes = raw.get('boxes', ())
            scores = raw.get('logits', raw.get('scores', ()))
            labels = raw.get('phrases', raw.get('labels', ()))
            raw = [
                {'bbox': box, 'confidence': float(np.asarray(score).max()), 'label': label}
                for box, score, label in zip(boxes, scores, labels)
            ]
        elif hasattr(raw, 'boxes') and hasattr(raw, 'logits') and hasattr(raw, 'phrases'):
            raw = [
                {'bbox': box, 'confidence': float(np.asarray(score).max()), 'label': label}
                for box, score, label in zip(raw.boxes, raw.logits, raw.phrases)
            ]
        return list(raw)

    def _materialize(    #
        self,
        raw_detections: Iterable[Any],
        image: np.ndarray,
        depth: np.ndarray,
        point_image: np.ndarray,
        step: int = 0,
        target: str = '',
        proposal_sources: Optional[Sequence[str]] = None,
    ) -> list[OpenVocabularyDetection]:
        output = []
        proposals = []
        raw_detections = list(raw_detections)
        if proposal_sources is not None and len(proposal_sources) != len(raw_detections):
            raise ValueError('proposal sources must align with detections')
        for index, raw in enumerate(raw_detections):
            source = proposal_sources[index] if proposal_sources is not None else 'legacy'
            label, confidence, bbox = self._parse_detection(raw, image.shape[:2])
            print(
                f"[GDINO_PARSED] step={step} pass={source} label={label!r} "
                f"score={confidence:.4f} bbox={bbox}",
                flush=True,
            )
            if confidence < self.config.confidence_threshold:
                print(
                    f"[SEMANTIC_DROP] step={step} pass={source} label={label!r} "
                    f"reason=confidence score={confidence:.4f} "
                    f"threshold={self.config.confidence_threshold}",
                    flush=True,
                )
                continue
            if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
                print(f"[SEMANTIC_DROP] step={step} pass={source} label={label!r} reason=empty_bbox", flush=True)
                continue
            proposals.append((label, confidence, bbox, source))
        use_vl = self.config.semantic_classifier == 'qwen-vl'
        if use_vl:
            proposals = self._select_proposals(proposals, step)
        categories = list(dict.fromkeys((*CLASSIFICATION_LABELS, *self._target_labels(target))))
        for label, confidence, bbox, source in proposals:
            mask = self._run_segmenter(image, bbox)
            if mask.shape != image.shape[:2]:
                raise ValueError('segmenter mask must align pixel-for-pixel with the input')
            valid = mask & np.isfinite(depth) & (depth > 0) & np.isfinite(point_image).all(axis=-1)
            world_points = point_image[valid]
            if len(world_points) < self.config.min_points:
                print(
                    f"[SEMANTIC_DROP] step={step} pass={source} label={label!r} "
                    f"reason=valid_points mask_pixels={int(mask.sum())} "
                    f"valid_points={len(world_points)} "
                    f"min_points={self.config.min_points}",
                    flush=True,
                )
                continue
            classification = {}
            if use_vl:
                # The VL model sees context and the marked proposal, not a black mask crop.
                crop = self._qwen_context_crop(image, bbox)
                classification = self.classifier.classify(crop, categories)
                final_label = classification['label']
                print(
                    f"[VL_CLASSIFIED] step={step} pass={source} proposal={label!r} final={final_label!r} "
                    f"model={classification['model']!r} bbox={bbox} "
                    f"reason={classification.get('reason')!r} response={classification.get('raw_text')!r}",
                    flush=True,
                )
                if final_label == 'unknown':
                    print(f"[SEMANTIC_DROP] step={step} pass={source} label={label!r} reason=vl_unknown", flush=True)
                    continue
                embedding, review_reason, clip_scores = None, 'qwen_vl_classified', {}
            else:
                embedding = self._embed_masked_crop(image, mask)
                final_label, review_reason, clip_scores = self._refine_label(label, embedding)
            output.append(
                OpenVocabularyDetection(
                    label=final_label,
                    confidence=confidence,
                    bbox=bbox,
                    mask=mask,
                    embedding=embedding,
                    centroid=tuple(float(value) for value in world_points.mean(axis=0)),
                    point_count=int(len(world_points)),
                    step=int(step),
                    raw_label=label,
                    label_refinement_reason=review_reason,
                    clip_label_scores=clip_scores,
                    label_source='qwen-vl' if use_vl else 'grounding-dino+clip',
                    classifier_model=classification.get('model'),
                    classifier_response=classification.get('raw_text'),
                    proposal_source=source,
                )
            )
        if use_vl:
            self._guard_screen_parts(output, image.shape[:2])
        return output

    def _guard_screen_parts(self, detections: list[OpenVocabularyDetection], image_shape) -> None:
        """Hold clipped screen strips without assuming a parent object category."""
        height, width = image_shape
        for item in detections:
            if item.label not in ('monitor', 'television'):
                continue
            x1, y1, x2, y2 = item.bbox
            box_width, box_height = x2 - x1, y2 - y1
            ratio = self.config.screen_edge_strip_aspect_ratio
            span = self.config.screen_edge_strip_min_span
            vertical_strip = (box_height / box_width >= ratio and box_height >= span * height
                              and (y1 <= 2 or y2 >= height - 2))
            horizontal_strip = (box_width / box_height >= ratio and box_width >= span * width
                                and (x1 <= 2 or x2 >= width - 2))
            if vertical_strip or horizontal_strip:
                item.semantic_eligible = False
                item.evidence_reason = 'clipped_screen_strip'
            if not item.semantic_eligible:
                print(
                    f'[SEMANTIC_HOLD] step={item.step} label={item.label!r} bbox={item.bbox} '
                    f'reason={item.evidence_reason}',
                    flush=True,
                )

    def _select_proposals(self, proposals: list, step: int) -> list:
        """Cheap class-agnostic NMS before either SAM or VL is called."""
        def iou(a, b):
            intersection = max(0.0, min(a[2], b[2]) - max(a[0], b[0])) * max(
                0.0, min(a[3], b[3]) - max(a[1], b[1])
            )
            union = (a[2] - a[0]) * (a[3] - a[1]) + (b[2] - b[0]) * (b[3] - b[1]) - intersection
            return intersection / union if union > 0 else 0.0

        # Source, not the detector's predicted label, determines priority.
        # A context box can never suppress or displace a surviving target-pass box.
        kept = []
        for proposal in sorted(proposals, key=lambda item: (item[3] == 'target', item[1]), reverse=True):
            label, _, bbox, source = proposal
            if any(iou(bbox, other[2]) >= self.config.proposal_nms_iou for other in kept):
                print(f"[SEMANTIC_DROP] step={step} pass={source} label={label!r} reason=duplicate_bbox", flush=True)
                continue
            if len(kept) >= self.config.qwen_vl_max_candidates:
                print(f"[SEMANTIC_DROP] step={step} pass={source} label={label!r} reason=vl_candidate_limit", flush=True)
                continue
            kept.append(proposal)
        return kept

    def _qwen_context_crop(self, image: np.ndarray, bbox: BBox) -> np.ndarray:
        """Preserve real RGB background; mark the original bbox inside a padded crop."""
        height, width = image.shape[:2]
        x1, y1, x2, y2 = bbox
        margin = self.config.qwen_vl_crop_margin
        left = max(0, int(np.floor(x1 - margin * (x2 - x1))))
        top = max(0, int(np.floor(y1 - margin * (y2 - y1))))
        right = min(width, int(np.ceil(x2 + margin * (x2 - x1))))
        bottom = min(height, int(np.ceil(y2 + margin * (y2 - y1))))
        crop = image[top:bottom, left:right].copy()
        if crop.size == 0:
            raise ValueError('cannot classify an empty context crop')
        # RGB red outline identifies which object to classify, retaining background.
        cv2.rectangle(crop, (max(0, int(x1) - left), max(0, int(y1) - top)),
                      (min(right - left - 1, int(x2) - left), min(bottom - top - 1, int(y2) - top)),
                      (255, 0, 0), 1)
        scale = min(1.0, self.config.qwen_vl_crop_max_side / max(crop.shape[:2]))
        if scale < 1.0:
            crop = cv2.resize(crop, (max(1, round(crop.shape[1] * scale)),
                                     max(1, round(crop.shape[0] * scale))), interpolation=cv2.INTER_AREA)
        return np.ascontiguousarray(crop)

    def _refine_label(
        self, raw_label: str, embedding: np.ndarray,
    ) -> tuple[str, str, dict[str, float]]:
        """Review a small confusion group using the already computed image vector.

        Only exact aliases are normalized. Arbitrary open-vocabulary phrases
        (including ambiguous compounds such as 'sofa bed') are not split or
        forcibly mapped to the context vocabulary.
        """
        label = ' '.join(str(raw_label).casefold().strip(' .').split())
        label = LABEL_ALIASES.get(label, label)
        if not self.config.label_refinement:
            # Television aliases are vocabulary normalization, independent of
            # whether the optional CLIP review is enabled.
            return (label if label == 'television' else raw_label), 'disabled', {}
        candidates = next((group for group in LABEL_REVIEW_GROUPS if label in group), None)
        if candidates is None:
            # Preserve unsupported phrases verbatim; canonicalize exact known aliases only.
            if label in self.config.context_categories:
                return label, 'outside_review_groups', {}
            return raw_label, 'outside_review_groups', {}
        if self.embedder is not None:
            # A custom image encoder need not share CLIP's text embedding space.
            return label, 'custom_embedding_space', {}

        matrix = self._label_text_matrices.get(candidates)
        if matrix is None:
            matrix = np.stack([
                self.embed_text(f'a photo of a {"potted plant" if name == "plant" else name}')
                for name in candidates
            ])
            self._label_text_matrices[candidates] = matrix
        scores = {name: float(score) for name, score in zip(candidates, matrix @ embedding)}
        if not all(np.isfinite(score) for score in scores.values()):
            raise ValueError('label review returned non-finite CLIP similarities')
        ranked = sorted(scores, key=scores.get, reverse=True)
        best, second = ranked[:2]
        if best == label:
            return label, 'clip_agrees', scores
        if scores[best] < self.config.label_refinement_min_similarity:
            return label, 'low_similarity_keep_original', scores
        if scores[best] - scores[second] < self.config.label_refinement_margin:
            return label, 'small_margin_keep_original', scores
        return best, 'clip_corrected', scores

    def _write_label_audit(self, detections: Sequence[OpenVocabularyDetection]) -> None:
        """Append once per fresh inference, never once per reuse of cached detections."""
        if not self.config.label_audit_path or not detections:
            return
        path = Path(self.config.label_audit_path)
        if not self._label_audit_ready:
            path.parent.mkdir(parents=True, exist_ok=True)
            self._label_audit_ready = True
        timestamp = time.time()
        with path.open('a', encoding='utf-8') as stream:
            for detection in detections:
                stream.write(json.dumps({
                    'timestamp': timestamp,
                    'step': detection.step,
                    'bbox': detection.bbox,
                    'raw_label': detection.raw_label,
                    'proposal_source': detection.proposal_source,
                    'final_label': detection.label,
                    'centroid': detection.centroid,
                    'semantic_eligible': detection.semantic_eligible,
                    'evidence_reason': detection.evidence_reason,
                    'label_source': detection.label_source,
                    'classifier_model': detection.classifier_model,
                    'classifier_response': detection.classifier_response,
                    # Keep the detector's score distinct from CLIP cosine similarity.
                    'dino_confidence': detection.confidence,
                    'reason': detection.label_refinement_reason,
                    'clip_scores': detection.clip_label_scores,
                    'required_margin': self.config.label_refinement_margin,
                    'required_similarity': self.config.label_refinement_min_similarity,
                }, ensure_ascii=False) + '\n')

    @staticmethod
    def _parse_detection(raw: Any, image_shape: tuple[int, int]) -> tuple[str, float, BBox]:
        if isinstance(raw, OpenVocabularyDetection):
            return raw.label, raw.confidence, raw.bbox
        if isinstance(raw, dict):
            label = str(raw.get('label', raw.get('phrase', 'object')))
            confidence = float(raw.get('confidence', raw.get('score', raw.get('logit', 1.0))))
            box = np.asarray(raw.get('bbox', raw.get('box')), dtype=float)
        else:
            label, confidence, box = raw
            box = np.asarray(box, dtype=float)
        if box.shape != (4,) or not np.isfinite(box).all():
            raise ValueError('detector bbox must contain four finite values')
        height, width = image_shape
        if np.max(np.abs(box)) <= 1.5:
            box = box * np.array([width, height, width, height], dtype=float)
        box[[0, 2]] = np.clip(box[[0, 2]], 0, width)
        box[[1, 3]] = np.clip(box[[1, 3]], 0, height)
        return label, confidence, tuple(float(value) for value in box)

    def _run_segmenter(self, image: np.ndarray, bbox: BBox) -> np.ndarray:
        segmenter = self.segmenter
        if hasattr(segmenter, 'segment'):
            mask = segmenter.segment(image, bbox)
        elif hasattr(segmenter, 'segment_bbox'):
            mask = segmenter.segment_bbox(image, list(bbox))
        else:
            mask = segmenter(image, bbox)
        return np.asarray(mask, dtype=bool)

    def _embed_masked_crop(self, image: np.ndarray, mask: np.ndarray) -> np.ndarray:
        rows, columns = np.nonzero(mask)
        if not len(rows):
            raise ValueError('cannot embed an empty mask')
        y1, y2 = rows.min(), rows.max() + 1
        x1, x2 = columns.min(), columns.max() + 1
        crop = image[y1:y2, x1:x2].copy()
        crop[~mask[y1:y2, x1:x2]] = 0
        vector = self.embedder(crop) if self.embedder is not None else self._clip_embed(crop)
        embedding = np.asarray(vector, dtype=np.float32).reshape(-1)
        norm = float(np.linalg.norm(embedding))
        if not np.isfinite(norm) or norm == 0:
            raise ValueError('embedder returned a zero or non-finite vector')
        return embedding / norm

    def _clip_embed(self, crop: np.ndarray) -> np.ndarray:
        self._ensure_clip()
        import torch

        inputs = self._clip_processor(images=crop, return_tensors='pt')
        inputs = {name: value.to(self._clip_device) for name, value in inputs.items()}
        with torch.inference_mode():
            features = self._clip_model.get_image_features(**inputs)
        return features[0].detach().cpu().numpy()

    def embed_text(self, text: str) -> np.ndarray:
        """Return a normalized CLIP text embedding for open-vocabulary matching."""

        if not str(text).strip():
            raise ValueError('text cannot be empty')
        self._ensure_clip()
        import torch

        inputs = self._clip_processor(text=[str(text)], return_tensors='pt', padding=True)
        inputs = {name: value.to(self._clip_device) for name, value in inputs.items()}
        with torch.inference_mode():
            features = self._clip_model.get_text_features(**inputs)
        embedding = features[0].detach().cpu().numpy().astype(np.float32)
        norm = float(np.linalg.norm(embedding))
        if not np.isfinite(norm) or norm <= 1e-12:
            raise ValueError('CLIP returned an invalid text embedding')
        return embedding / norm

    def _ensure_clip(self):
        if self._clip_model is None:
            import torch
            from transformers import CLIPModel, CLIPProcessor

            device = self.config.clip_device or ('cuda' if torch.cuda.is_available() else 'cpu')    
            self._clip_processor = CLIPProcessor.from_pretrained(
                self.config.clip_model_name,
                local_files_only=True,
            )
            self._clip_model = CLIPModel.from_pretrained(
                self.config.clip_model_name,
                local_files_only=True,
            ).to(device)
            self._clip_model.eval()
            self._clip_device = device


__all__ = [
    'AgentVLMBackend',
    'OpenVocabularyDetection',
    'OpenVocabularyPerception',
    'OpenVocabularyPerceptionConfig',
]
